# Generated by Django 5.0.3 on 2025-12-10 15:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Meu Projeto', help_text='Nome que aparecerá no site e admin', max_length=200, verbose_name='Nome do Projeto')),
                ('project_slogan', models.CharField(blank=True, help_text='Slogan ou tagline do projeto', max_length=255, verbose_name='Slogan')),
                ('project_description', models.TextField(blank=True, help_text='Descrição detalhada do projeto', verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, help_text='Logo principal do projeto (recomendado: 300x100px)', null=True, upload_to='config/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Logo Principal')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo para modo escuro (opcional)', null=True, upload_to='config/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Logo Modo Escuro')),
                ('favicon', models.ImageField(blank=True, help_text='Ícone do site (recomendado: 32x32px ou 16x16px)', null=True, upload_to='config/icons/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png'])], verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, help_text='E-mail principal para contato', max_length=254, verbose_name='E-mail Principal')),
                ('phone', models.CharField(blank=True, help_text='Telefone para contato (ex: +55 11 99999-9999)', max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Número do WhatsApp (ex: +5511999999999)', max_length=20, verbose_name='WhatsApp')),
                ('address_street', models.CharField(blank=True, help_text='Rua, avenida, etc.', max_length=255, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, help_text='Apartamento, sala, bloco, etc.', max_length=100, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, help_text='Sigla do estado (ex: SP, RJ)', max_length=2, verbose_name='Estado')),
                ('address_zipcode', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('address_country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada de latitude para mapa', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada de longitude para mapa', max_digits=10, null=True, verbose_name='Longitude')),
                ('facebook_url', models.URLField(blank=True, max_length=255, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, max_length=255, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, max_length=255, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, max_length=255, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, max_length=255, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, max_length=255, verbose_name='TikTok')),
                ('business_hours', models.TextField(blank=True, help_text='Ex: Seg-Sex: 9h às 18h | Sáb: 9h às 13h', verbose_name='Horário de Funcionamento')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255, verbose_name='Palavras-chave (SEO)')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição que aparece nos resultados de busca (máx. 160 caracteres)', max_length=160, verbose_name='Meta Descrição (SEO)')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Ex: G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Ex: GTM-XXXXXXX', max_length=50, verbose_name='Google Tag Manager ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('custom_head_scripts', models.TextField(blank=True, help_text='Scripts que serão inseridos no <head>', verbose_name='Scripts Personalizados (HEAD)')),
                ('custom_body_scripts', models.TextField(blank=True, help_text='Scripts que serão inseridos antes do </body>', verbose_name='Scripts Personalizados (BODY)')),
                ('is_active', models.BooleanField(default=True, help_text='Define se as configurações estão ativas', verbose_name='Ativo')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Ativa o modo de manutenção do site', verbose_name='Modo Manutenção')),
                ('maintenance_message', models.TextField(blank=True, default='Estamos em manutenção. Voltaremos em breve!', help_text='Mensagem exibida quando o site está em manutenção', verbose_name='Mensagem de Manutenção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Projeto',
                'verbose_name_plural': 'Configurações do Projeto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('github', 'GitHub'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('medium', 'Medium'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('spotify', 'Spotify'), ('other', 'Outro')], max_length=50, verbose_name='Plataforma')),
                ('custom_name', models.CharField(blank=True, help_text='Use apenas se escolher "Outro"', max_length=100, verbose_name='Nome Customizado')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('icon_class', models.CharField(blank=True, help_text='Ex: fab fa-facebook (Font Awesome)', max_length=100, verbose_name='Classe do Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('project_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='configs_project.projectconfig', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Link de Rede Social',
                'verbose_name_plural': 'Links de Redes Sociais',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
