version: '3.9'

services:
  djangoservice:
    container_name: ${CONTAINER_NAME_DJANGO}
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do container para a porta 8000 do host
    build:
      context: .
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - psqlservice
    networks:
      - alter_network

  psqlservice:
    container_name: ${CONTAINER_NAME_PSQL}
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    # A porta não precisa ser exposta para o host, a menos que você queira acessá-la de fora do Docker
    networks:
      - alter_network

  nginx:
    image: nginx:alpine
    container_name: nginx_${CONTAINER_NAME_DJANGO}

    volumes:
      - ./data/web/static:/usr/share/nginx/html/static:ro
      - ./data/web/media:/usr/share/nginx/html/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - djangoservice
    networks:
      - traefik_network # Conecta à rede do Traefik
      - alter_network


networks:
  default:
    driver: bridge
  alter_network:
    driver: bridge
  traefik_network:
    external: true


