# Generated by Django 5.0.3 on 2025-08-14 22:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('objetivo', models.TextField()),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, unique=True, verbose_name='Número do Contrato')),
                ('objeto', models.TextField()),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('situacao', models.CharField(max_length=100, verbose_name='Situação')),
                ('tipo_contrato', models.CharField(max_length=100, verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('certidoes_anexadas', models.FileField(blank=True, null=True, upload_to='certidoes/', verbose_name='Certidões Anexadas')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RADIO', 'Rádio'), ('TV', 'TV'), ('WEB', 'Web')], max_length=5)),
                ('formato', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='ClipagemAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_chave', models.CharField(max_length=255, verbose_name='Palavra-chave')),
                ('fonte', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('data_coleta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Coleta')),
                ('tipo_midia', models.CharField(choices=[('BLOG', 'Blog'), ('REDESOCIAL', 'Rede Social'), ('SITE', 'Site')], max_length=20, verbose_name='Tipo de Mídia')),
                ('conteudo_html', models.TextField(blank=True, null=True, verbose_name='Conteúdo HTML')),
                ('imagem_salva', models.ImageField(blank=True, null=True, upload_to='clipagens/', verbose_name='Imagem Salva')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipagens', to='midia.campanha')),
            ],
            options={
                'verbose_name': 'Clipagem Automática',
                'verbose_name_plural': 'Clipagens Automáticas',
            },
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='midia.contrato')),
            ],
            options={
                'verbose_name': 'Aditivo',
                'verbose_name_plural': 'Aditivos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='midia.contrato')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='ProducaoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data_producao', models.DateField(verbose_name='Data de Produção')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='midia.evento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='midia.fornecedor')),
            ],
            options={
                'verbose_name': 'Produção de Mídia',
                'verbose_name_plural': 'Produções de Mídia',
            },
        ),
        migrations.CreateModel(
            name='ConferenciaMidiaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_veiculo', models.URLField(max_length=500, verbose_name='URL do Veículo')),
                ('data_verificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Verificação')),
                ('hash_encontrado', models.CharField(blank=True, max_length=255, null=True)),
                ('status_verificacao', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('NAO_ENCONTRADO', 'Não encontrado')], max_length=20, verbose_name='Status')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='midia.producaomidia')),
            ],
            options={
                'verbose_name': 'Conferência de Mídia Digital',
                'verbose_name_plural': 'Conferências de Mídia Digital',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='midia.secretaria'),
        ),
        migrations.CreateModel(
            name='UsoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midia.campanha')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midia.producaomidia')),
            ],
            options={
                'verbose_name': 'Uso em Campanha',
                'verbose_name_plural': 'Usos em Campanha',
                'unique_together': {('campanha', 'producao')},
            },
        ),
        migrations.AddField(
            model_name='campanha',
            name='producoes',
            field=models.ManyToManyField(related_name='campanhas', through='midia.UsoCampanha', to='midia.producaomidia'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(blank=True, help_text='Ex: Administrador, Usuário Padrão', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='midia.secretaria')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculacoes', to='midia.midia')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculacoes', to='midia.producaomidia')),
            ],
            options={
                'verbose_name': 'Veiculação',
                'verbose_name_plural': 'Veiculações',
            },
        ),
    ]
